version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 18, 16, 14.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye

    environment:
      PGUSER: postgres
      #you probably want to change this
      PGPASSWORD: postgres
      PGHOST: db
      # Change this if you don't use the create_table.sql
      PGDATABASE: shortldb
    ports:
      - 8080:3000	

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      #you probably want to change this
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shortldb

volumes:
  postgres-data:
